### ISSUE TITLE
throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +

### ISSUE THREAD

**Issue by qingdujun** [Mawalu/node-homeassistant#7]
**STEP 1**

/home/xxx/node-homeassistant$ npm install

-  SOME OUTPUT
> uws@9.14.0 install /home/xxx/node-homeassistant/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm WARN node-homeassistant@1.4.1 No repository field.

added 1 package from 1 contributor and audited 1 package in 10.379s
found 0 vulnerabilities

...

**STEP 2**

/home/xxx/node-homeassistant$ node examples/simple.js

- SOME ERR

/home/xxx/node-homeassistant/node_modules/uws/uws.js:38
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/home/xxx/node-homeassistant/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/home/xxx/node-homeassistant/node_modules/uws/uws.js:42:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/xxx/node-homeassistant/index.js:2:19)

**Comment by mawalu** [comment]
It seems like uws is no longer published on npm and I can't find the source anywhere else. I switched back to ws in `v1.5.0`. The problem should be fixed now.
